# -*- coding: utf-8 -*-
"""Percorso_Laurea.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14gqBLJZdtR9ogV_VMHxx0SmpZ2Z_vlM_
"""

import time
import sys
import urllib.parse

def loading_bar(text, duration=3, steps=20):
    print(text)
    for i in range(steps + 1):
        percent = int((i / steps) * 100)
        bar = "#" * i + "-" * (steps - i)
        sys.stdout.write(f"\r[{bar}] {percent}%")
        sys.stdout.flush()
        time.sleep(duration / steps)
    print("\n")

esami_superati = 0
esami_rimanenti = 4
tesi = False
discussione = False
laureato = False

# Lista fittizia di materie
lista_materie = [
    {"nome": "Analisi Matematica", "cfu": 9},
    {"nome": "Sistemi Operativi", "cfu": 6},
    {"nome": "Intelligenza Artificiale", "cfu": 6},
    {"nome": "Machine Learning", "cfu": 6}
]

for materia in lista_materie:
    print(f"\n📚 Materia: {materia['nome']} - CFU: {materia['cfu']}")
    loading_bar("📖 Studio in corso...", duration=2)
    loading_bar("📝 Esame in corso...", duration=2)
    print("✅ Esame superato! Andiamo al prossimo!\n")
    esami_superati += 1
    esami_rimanenti -= 1
    time.sleep(1)

if esami_rimanenti == 0:
    print("🎓 Tutti gli esami sono finiti!\n")
    time.sleep(1)
    loading_bar("🧠 Si inizia a scrivere la tesi...", duration=2.5)
    loading_bar("🤖 Studio su AI e Machine Learning...", duration=2)
    loading_bar("🛠️ Tesi quasi completata!", duration=1.5)
    loading_bar("📚 Tesi completata!", duration=1)
    tesi = True

if tesi:
    loading_bar("🎤 Preparazione per la discussione...", duration=2)
    loading_bar("🎙️ Discussione in corso...", duration=2.5)
    print("🏁 Discussione completata!\n")
    discussione = True

if discussione:
    laureato = True
    print("🎉 Percorso completato: finalmente sei LAUREATO!")
    print("👏 Auguri al neo Dottore Alessandro! 🥳🍾🎂\n")
    time.sleep(1)


# Chiedi il messaggio all'utente
messaggio = input("💬 Vuoi lasciare un messaggio al Dottore?\n> ")

# Prepara il contenuto della mail
destinatario = "Alessandromultari00@gmail.com"
oggetto = "Messaggio per la laurea"
corpo = messaggio

# Codifica l'URL mailto
mailto_link = f"mailto:{destinatario}?subject={urllib.parse.quote(oggetto)}&body={urllib.parse.quote(corpo)}"

# Stampa il link cliccabile
from IPython.display import HTML, display
display(HTML(f"""
<h3>📨 Clicca per inviare il tuo messaggio via email!</h3>
<p><a href="{mailto_link}" target="_blank">Invia la tua email a {destinatario}</a></p>
"""))

# Messaggio finale degli invitati
print(f"\n📝Messaggio inviato via mail!")